<a href="https://colab.research.google.com/github/HarisJafri-xcode/Data-Analyst-in-Python/blob/main/Data-Manipulation-with-Pandas/Aggregating_Data_Frame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Summary Statistics

In [ ]:
# Loading Important Data Science Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Storing file path
file_path = "https://raw.githubusercontent.com/HarisJafri-xcode/Python-Session-DataSets/refs/heads/main/Data_Manipulation/sales.csv"

In [ ]:
# Loading Dataset inside Dataframe
sales = pd.read_csv(file_path, index_col=0)

In [ ]:
# displaying first few rows of the DataFrame
sales.head()

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
1,1,A,1,2010-03-05,21827.90,False,8.055556,0.693452,8.106
2,1,A,1,2010-04-02,57258.43,False,16.816667,0.718284,7.808
3,1,A,1,2010-05-07,17413.94,False,22.527778,0.748928,7.808
4,1,A,1,2010-06-04,17558.09,False,27.050000,0.714586,7.808

In [ ]:
# Info about the sales DataFrame
sales.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10774 entries, 0 to 10773
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   store                 10774 non-null  int64
 1   type                  10774 non-null  object
 2   department            10774 non-null  int64
 3   date                  10774 non-null  object
 4   weekly_sales          10774 non-null  float64
 5   is_holiday            10774 non-null  bool
 6   temperature_c         10774 non-null  float64
 7   fuel_price_usd_per_l  10774 non-null  float64
 8   unemployment          10774 non-null  float64
dtypes: bool(1), float64(4), int64(2), object(2)
memory usage: 1.0+ MB

In [ ]:
# Mean of Weekly sales column
sales['weekly_sales'].mean()

np.float64(23843.95014850566)

In [ ]:
# printing Mean of Weekly sales column
print(sales['weekly_sales'].mean())

23843.95014850566

In [ ]:
# Median of Weekly sales column
sales['weekly_sales'].median()

12049.064999999999

In [ ]:
# Converting Date Column to pandas datetime dtype
sales['date'] = pd.to_datetime(sales['date'],format='%Y-%m-%d')

In [ ]:
# Print the maximum of the date column
print(sales['date'].max())

2012-10-26 00:00:00

In [ ]:
# Print the minimum of the date column
print(sales['date'].min())

2010-02-05 00:00:00

In [ ]:
# A custom IQR function
def iqr(column):
    return column.quantile(0.75) - column.quantile(0.25)

# Display IQR of the temperature_c column
sales['temperature_c'].agg(iqr)

np.float64(16.583333333333336)

In [ ]:
# Applying iqr Function on 3 Columns
sales[["temperature_c", 'fuel_price_usd_per_l', 'unemployment']].agg(iqr)

temperature_c           16.583333
fuel_price_usd_per_l     0.073176
unemployment             0.565000
dtype: float64

In [ ]:
# Applying iqr, median and mean Function on 3 Columns
sales[["temperature_c", "fuel_price_usd_per_l", "unemployment"]].agg([iqr, "median","mean"])

        temperature_c  fuel_price_usd_per_l  unemployment
iqr         16.583333              0.073176      0.565000
median      16.966667              0.743381      8.099000
mean        15.731978              0.749746      8.082009

In [ ]:
# Subsetting Dataframe where Store == 1 & Department == 1
mask = (sales['store'] == 1) & (sales['department'] == 1)
sales_1_1 = sales[mask].copy()

In [ ]:
# Sorting Via Date
sales_1_1 = sales_1_1.sort_values('date')

In [ ]:
# Adding a New Column
sales_1_1['cum_weekly_sales'] = sales_1_1['weekly_sales'].cumsum()

In [ ]:
# Displaying Dataframe with 3 Columns
sales_1_1[["date", "weekly_sales", "cum_weekly_sales"]]

         date  weekly_sales  cum_weekly_sales
0  2010-02-05      24924.50          24924.50
1  2010-03-05      21827.90          46752.40
2  2010-04-02      57258.43         104010.83
3  2010-05-07      17413.94         121424.77
4  2010-06-04      17558.09         138982.86
5  2010-07-02      16333.14         155316.00
6  2010-08-06      17508.41         172824.41
7  2010-09-03      16241.78         189066.19
8  2010-10-01      20094.19         209160.38
9  2010-11-05      34238.88         243399.26
10 2010-12-03      22517.56         265916.82
11 2011-01-07      15984.24         281901.06

# Counting

In [ ]:
# Dropping all Similar Combinations of Store and Type
store_types = sales.drop_duplicates(subset=['store','type'])
store_types.head()

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
901,2,A,1,2010-02-05,35034.06,False,4.550000,0.679451,8.324
1798,4,A,1,2010-02-05,38724.42,False,6.533333,0.686319,8.623
2699,6,A,1,2010-02-05,25619.00,False,4.683333,0.679451,7.259
3593,10,B,1,2010-02-05,40212.84,False,12.411111,0.782478,9.765

In [ ]:
# Dropping all Similar Combinations of Store and Department
store_depts = sales.drop_duplicates(subset=['store','department'])
store_depts.head()

,store,type,department,date,weekly_sales,is_holiday,temperature_c,fuel_price_usd_per_l,unemployment
0,1,A,1,2010-02-05,24924.50,False,5.727778,0.679451,8.106
12,1,A,2,2010-02-05,50605.27,False,5.727778,0.679451,8.106
24,1,A,3,2010-02-05,13740.12,False,5.727778,0.679451,8.106
36,1,A,4,2010-02-05,39954.04,False,5.727778,0.679451,8.106
48,1,A,5,2010-02-05,32229.38,False,5.727778,0.679451,8.106

In [ ]:
# Extracting Rows that have is_holiday set to True and dropping Duplicates on date Column
holiday_dates = sales[sales['is_holiday'] == True].drop_duplicates(subset='date')

In [ ]:
# Extracting date Column
holiday_dates['date']

498    2010-09-10
691    2011-11-25
2315   2010-02-12
6735   2012-09-07
6810   2010-12-31
6815   2012-02-10
6820   2011-09-09
Name: date, dtype: datetime64[ns]

In [ ]:
# How many distinct values of Store Types
store_types["type"].value_counts()

type
A    11
B     1
Name: count, dtype: int64

In [ ]:
# How many distinct values of Store Types in %
store_types["type"].value_counts(normalize=True)

type
A    0.916667
B    0.083333
Name: proportion, dtype: float64

# Grouped Summary Statistics

## What percent of sales occurred at each store type?

In [ ]:
# Calc total weekly sales
sales_all = sales["weekly_sales"].sum()

# Subset for type A stores, calc total weekly sales
sales_A = sales[sales["type"] == "A"]["weekly_sales"].sum()

# Subset for type B stores, calc total weekly sales
sales_B = sales[sales["type"] == "B"]["weekly_sales"].sum()

# Subset for type C stores, calc total weekly sales
sales_C = sales[sales["type"] == "C"]["weekly_sales"].sum()

# Get proportion for each type
sales_propn_by_type = [sales_A, sales_B, sales_C] / sales_all
print(sales_propn_by_type)

[0.9097747 0.0902253 0.       ]

In [ ]:
# Group by type; calc total weekly sales
sales_by_type = sales.groupby("type")["weekly_sales"].sum()

# Get proportion for each type
sales_propn_by_type = sales_by_type / sales_by_type.sum()
print(sales_propn_by_type)

type
A    0.909775
B    0.090225
Name: weekly_sales, dtype: float64

## Multiple Grouped Summaries

In [ ]:
# Grouping by Type and finding multiple Statistics
sales_stats = sales.groupby("type")["weekly_sales"].agg(["min", "max", "mean", "median"])
sales_stats

         min        max          mean    median
type
A    -1098.0  293966.05  23674.667242  11943.92
B     -798.0  232558.51  25696.678370  13336.08

In [ ]:
# Grouping by Type and finding multiple Statistics
unemp_fuel_stats = sales.groupby('type')[['unemployment', 'fuel_price_usd_per_l']].agg(['mean', 'median'])
unemp_fuel_stats

     unemployment        fuel_price_usd_per_l
             mean median                 mean    median
type
A        7.972611  8.067             0.744619  0.735455
B        9.279323  9.199             0.805858  0.803348